// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: active_recordings.sql

package database

import (
	"context"
	"time"
)

const listActiveRecordings = `-- name: ListActiveRecordings :many
SELECT 
    r.id,
    r.task_id,
    r.status,
    r.start_time,
    r.file_path,
    t.name as task_name
FROM recordings r
JOIN tasks t ON r.task_id = t.id
WHERE r.status = 'RECORDING'
ORDER BY r.start_time DESC
`

type ListActiveRecordingsRow struct {
	ID        int64
	TaskID    int64
	Status    string
	StartTime time.Time
	FilePath  string
	TaskName  string
}

func (q *Queries) ListActiveRecordings(ctx context.Context) ([]ListActiveRecordingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveRecordings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveRecordingsRow
	for rows.Next() {
		var i ListActiveRecordingsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Status,
			&i.StartTime,
			&i.FilePath,
			&i.TaskName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
