// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Recording struct {
	ID        int64
	TaskID    int64
	Status    string
	StartTime time.Time
	EndTime   sql.NullTime
	FilePath  string
}

type Task struct {
	ID                int64
	Name              string
	TargetUrl         string
	IsEnabled         bool
	IsDeleted         bool
	FilenameTemplate  string
	CustomCss         string
	Fps               int64
	Crf               int64
	TimeOverlay       bool
	TimeOverlayConfig string
	CreatedAt         time.Time
}

type User struct {
	ID           int64
	Username     string
	PasswordHash string
	CreatedAt    time.Time
}
