// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRecording = `-- name: CreateRecording :one
INSERT INTO recordings (task_id, status, file_path, start_time) 
VALUES (?, ?, ?, CURRENT_TIMESTAMP) RETURNING id, task_id, status, start_time, end_time, file_path
`

type CreateRecordingParams struct {
	TaskID   int64
	Status   string
	FilePath string
}

func (q *Queries) CreateRecording(ctx context.Context, arg CreateRecordingParams) (Recording, error) {
	row := q.db.QueryRowContext(ctx, createRecording, arg.TaskID, arg.Status, arg.FilePath)
	var i Recording
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Status,
		&i.StartTime,
		&i.EndTime,
		&i.FilePath,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (name, target_url, is_enabled, filename_template, custom_css, fps, crf) VALUES (?, ?, 0, ?, ?, ?, ?) RETURNING id, name, target_url, is_enabled, is_deleted, filename_template, custom_css, fps, crf, created_at
`

type CreateTaskParams struct {
	Name             string
	TargetUrl        string
	FilenameTemplate string
	CustomCss        string
	Fps              int64
	Crf              int64
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.Name,
		arg.TargetUrl,
		arg.FilenameTemplate,
		arg.CustomCss,
		arg.Fps,
		arg.Crf,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TargetUrl,
		&i.IsEnabled,
		&i.IsDeleted,
		&i.FilenameTemplate,
		&i.CustomCss,
		&i.Fps,
		&i.Crf,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash) VALUES (?, ?) RETURNING id, username, password_hash, created_at
`

type CreateUserParams struct {
	Username     string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRecording = `-- name: DeleteRecording :exec
DELETE FROM recordings WHERE id = ?
`

func (q *Queries) DeleteRecording(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRecording, id)
	return err
}

const deleteTask = `-- name: DeleteTask :exec
UPDATE tasks SET is_deleted = 1, is_enabled = 0 WHERE id = ?
`

func (q *Queries) DeleteTask(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const disableTask = `-- name: DisableTask :exec
UPDATE tasks SET is_enabled = 0 WHERE id = ?
`

func (q *Queries) DisableTask(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, disableTask, id)
	return err
}

const enableTask = `-- name: EnableTask :exec
UPDATE tasks SET is_enabled = 1 WHERE id = ?
`

func (q *Queries) EnableTask(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, enableTask, id)
	return err
}

const getRecording = `-- name: GetRecording :one
SELECT id, task_id, status, start_time, end_time, file_path FROM recordings WHERE id = ? LIMIT 1
`

func (q *Queries) GetRecording(ctx context.Context, id int64) (Recording, error) {
	row := q.db.QueryRowContext(ctx, getRecording, id)
	var i Recording
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Status,
		&i.StartTime,
		&i.EndTime,
		&i.FilePath,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, name, target_url, is_enabled, is_deleted, filename_template, custom_css, fps, crf, created_at FROM tasks WHERE id = ? LIMIT 1
`

func (q *Queries) GetTask(ctx context.Context, id int64) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TargetUrl,
		&i.IsEnabled,
		&i.IsDeleted,
		&i.FilenameTemplate,
		&i.CustomCss,
		&i.Fps,
		&i.Crf,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, created_at FROM users WHERE username = ? LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const listEnabledTasks = `-- name: ListEnabledTasks :many
SELECT id, name, target_url, is_enabled, is_deleted, filename_template, custom_css, fps, crf, created_at FROM tasks WHERE is_enabled = 1
`

func (q *Queries) ListEnabledTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TargetUrl,
			&i.IsEnabled,
			&i.IsDeleted,
			&i.FilenameTemplate,
			&i.CustomCss,
			&i.Fps,
			&i.Crf,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordings = `-- name: ListRecordings :many
SELECT r.id, r.task_id, r.status, r.start_time, r.end_time, r.file_path, t.name as task_name 
FROM recordings r 
JOIN tasks t ON r.task_id = t.id 
ORDER BY r.start_time DESC
`

type ListRecordingsRow struct {
	ID        int64
	TaskID    int64
	Status    string
	StartTime time.Time
	EndTime   sql.NullTime
	FilePath  string
	TaskName  string
}

func (q *Queries) ListRecordings(ctx context.Context) ([]ListRecordingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecordings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecordingsRow
	for rows.Next() {
		var i ListRecordingsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Status,
			&i.StartTime,
			&i.EndTime,
			&i.FilePath,
			&i.TaskName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, name, target_url, is_enabled, is_deleted, filename_template, custom_css, fps, crf, created_at FROM tasks WHERE is_deleted = 0 ORDER BY created_at DESC
`

func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TargetUrl,
			&i.IsEnabled,
			&i.IsDeleted,
			&i.FilenameTemplate,
			&i.CustomCss,
			&i.Fps,
			&i.Crf,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecordingStatus = `-- name: UpdateRecordingStatus :exec
UPDATE recordings SET status = ?, end_time = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateRecordingStatusParams struct {
	Status string
	ID     int64
}

func (q *Queries) UpdateRecordingStatus(ctx context.Context, arg UpdateRecordingStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateRecordingStatus, arg.Status, arg.ID)
	return err
}

const updateTask = `-- name: UpdateTask :exec
UPDATE tasks 
SET name = ?, target_url = ?, filename_template = ?, custom_css = ?, fps = ?, crf = ?
WHERE id = ?
`

type UpdateTaskParams struct {
	Name             string
	TargetUrl        string
	FilenameTemplate string
	CustomCss        string
	Fps              int64
	Crf              int64
	ID               int64
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) error {
	_, err := q.db.ExecContext(ctx, updateTask,
		arg.Name,
		arg.TargetUrl,
		arg.FilenameTemplate,
		arg.CustomCss,
		arg.Fps,
		arg.Crf,
		arg.ID,
	)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = ? WHERE username = ?
`

type UpdateUserPasswordParams struct {
	PasswordHash string
	Username     string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.Username)
	return err
}
